Pojďme si procvičit nabyté znalosti analýzou dat o zpoždění vlaků ve Francii. Data najdete [zde](https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-26/full_trains.csv), podrobnosti k datasetu najdete na Githubu.

Následující úkoly jsou spíše doporučení. Pokud bys k analýze přistupovala jinak, směle do toho! Klidně k řešení napiš poznámku, o co se snažíš a s čím případně potřebuješ pomoci, a kouč ti poradí. Zkus si u jednotlivých úkolů procvičit také grafy :)

## 0. Ve kterém roce/měsíci bylo nejvíc zrušených vlaků?

In [1]:
import pandas as pd

In [4]:
trains = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-26/full_trains.csv")
trains

,year,month,service,departure_station,arrival_station,journey_time_avg,total_num_trips,num_of_canceled_trains,comment_cancellations,num_late_at_departure,...,delay_cause_external_cause,delay_cause_rail_infrastructure,delay_cause_traffic_management,delay_cause_rolling_stock,delay_cause_station_management,delay_cause_travelers,num_greater_15_min_late,avg_delay_late_greater_15_min,num_greater_30_min_late,num_greater_60_min_late
0,2017,9,National,PARIS EST,METZ,85.133779,299,0,NaN,15,...,0.250000,0.000000,0.166667,0.416667,0.166667,0.000000,6.0,24.033333,1.0,0.0
1,2017,9,National,REIMS,PARIS EST,47.064516,218,1,NaN,10,...,0.250000,0.375000,0.125000,0.125000,0.062500,0.062500,9.0,21.498148,1.0,0.0
2,2017,9,National,PARIS EST,STRASBOURG,116.234940,333,1,NaN,20,...,0.214286,0.214286,0.071429,0.285714,0.214286,0.000000,14.0,24.694048,3.0,0.0
3,2017,9,National,PARIS LYON,AVIGNON TGV,161.089583,481,1,NaN,36,...,0.155172,0.120690,0.310345,0.344828,0.034483,0.034483,40.0,34.047500,21.0,5.0
4,2017,9,National,PARIS LYON,BELLEGARDE (AIN),164.452632,190,0,NaN,16,...,0.166667,0.250000,0.250000,0.305556,0.000000,0.027778,26.0,28.401282,8.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5457,2018,9,NaN,ANGOULEME,PARIS MONTPARNASSE,130.690840,262,0,NaN,127,...,0.108696,0.369565,0.326087,0.108696,0.000000,0.086957,15.0,4.893003,6.0,1.0
5458,2018,9,NaN,TOULOUSE MATABIAU,PARIS MONTPARNASSE,263.584270,178,0,NaN,13,...,0.320000,0.320000,0.080000,0.240000,0.000000,0.040000,25.0,7.000936,10.0,1.0
5459,2018,9,NaN,PARIS MONTPARNASSE,TOURS,78.931818,176,0,NaN,24,...,0.050000,0.400000,0.300000,0.250000,0.000000,0.000000,10.0,4.351136,5.0,1.0
5460,2018,9,NaN,PARIS MONTPARNASSE,LAVAL,89.436893,206,0,NaN,15,...,0.000000,0.250000,0.250000,0.500000,0.000000,0.000000,4.0,2.421278,0.0,0.0
5461,2018,9,NaN,ST MALO,PARIS MONTPARNASSE,173.555556,90,0,NaN,4,...,0.000000,0.000000,0.250000,0.250000,0.500000,0.000000,1.0,2.931111,0.0,0.0

In [6]:
trains.dtypes

year                                 int64
month                                int64
service                             object
departure_station                   object
arrival_station                     object
journey_time_avg                   float64
total_num_trips                      int64
num_of_canceled_trains               int64
comment_cancellations              float64
num_late_at_departure                int64
avg_delay_late_at_departure        float64
avg_delay_all_departing            float64
comment_delays_at_departure        float64
num_arriving_late                  float64
avg_delay_late_on_arrival          float64
avg_delay_all_arriving             float64
comment_delays_on_arrival           object
delay_cause_external_cause         float64
delay_cause_rail_infrastructure    float64
delay_cause_traffic_management     float64
delay_cause_rolling_stock          float64
delay_cause_station_management     float64
delay_cause_travelers              float64
num_greater_15_min_late            float64
avg_delay_late_greater_15_min      float64
num_greater_30_min_late            float64
num_greater_60_min_late            float64
dtype: object

In [19]:
trains["num_of_canceled_trains"].max()

279

In [32]:
trains.loc[trains['num_of_canceled_trains'].idxmax()][["year", "month", "num_of_canceled_trains"]]

year                      2018
month                        4
num_of_canceled_trains     279
Name: 4528, dtype: object

## 1. Která stanice je „nejhorší“? Např. dle počtu zrušených vlaků, největšího zpoždění na odjezdu apod.? Pozor, pro některé stanice jsou data jen z roku 2018.

In [33]:
trains.loc[trains['num_of_canceled_trains'].idxmax()][["departure_station", "arrival_station", "num_of_canceled_trains"]]

departure_station           BORDEAUX ST JEAN
arrival_station           PARIS MONTPARNASSE
num_of_canceled_trains                   279
Name: 4528, dtype: object

In [34]:
trains[trains.avg_delay_late_at_departure == trains.avg_delay_late_at_departure.max()][["departure_station", "arrival_station", "avg_delay_late_at_departure"]]

     departure_station arrival_station  avg_delay_late_at_departure
1996            ITALIE      PARIS LYON                   173.571429

In [38]:
trains[trains.avg_delay_all_arriving == trains.avg_delay_all_arriving.max()][["departure_station", "arrival_station", "avg_delay_all_arriving"]]

     departure_station arrival_station  avg_delay_all_arriving
5212    LYON PART DIEU          RENNES                36.81687

In [43]:
trains.isna().sum()

year                                  0
month                                 0
service                            1430
departure_station                     0
arrival_station                       0
journey_time_avg                      0
total_num_trips                       0
num_of_canceled_trains                0
comment_cancellations              5462
num_late_at_departure                 0
avg_delay_late_at_departure           0
avg_delay_all_departing               0
comment_delays_at_departure        5462
num_arriving_late                     9
avg_delay_late_on_arrival             9
avg_delay_all_arriving                0
comment_delays_on_arrival          3921
delay_cause_external_cause          170
delay_cause_rail_infrastructure     170
delay_cause_traffic_management      170
delay_cause_rolling_stock           170
delay_cause_station_management      170
delay_cause_travelers               170
num_greater_15_min_late               5
avg_delay_late_greater_15_min         5
num_greater_30_min_late               5
num_greater_60_min_late               5
dtype: int64

## 2. Na které trati je průměrně největší zpoždění?

In [39]:
trains[trains.avg_delay_late_at_departure == trains.avg_delay_late_at_departure.max()][["departure_station", "arrival_station", "avg_delay_late_at_departure"]]

     departure_station arrival_station  avg_delay_late_at_departure
1996            ITALIE      PARIS LYON                   173.571429

## 3. Zkus zjistit, jestli je nějaká závislost na roční době – např. zda je v zimě více zpoždění než v létě, které měsíce jsou nejrizikovější z hlediska zpoždění apod.

## 4. Cokoli dalšího tě zajímá aneb prostor pro tvé experimenty: Pochlub se funkčním kódem s okomentovaným řešením, případně kouče požádej o radu, pokud něco nefunguje. Pokud ti vyjde nějaký zajímavý graf, pochlub se s ním v kanále #projekty na Slacku!